check now

diff --git a/.github/workflows/updateIPLists.yml b/.github/workflows/updateIPLists.yml
--- a/.github/workflows/updateIPLists.yml
+++ b/.github/workflows/updateIPLists.yml
@@ -42,10 +42,13 @@ jobs:
       - name: Fetch new Imperva IPs
         id: newAllowlistedIpList
         run: |
-          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
-          echo "new_array<<$EOF" >> "$GITHUB_ENV"
-          curl -s --data "resp_format=json" https://my.imperva.com/api/integration/v1/ips | jq -r '.ipRanges' >> "$GITHUB_ENV"
-          echo "$EOF" >> "$GITHUB_ENV"
+          new_array=$(curl -s --data "resp_format=json" https://my.imperva.com/api/integration/v1/ips | jq -r ".ipRange")
+          if [[ -z "$new_array" ]]; then
+            echo "::error::Failed to fetch new array."
+            exit 1
+          else
+            echo "$new_array" > "${GITHUB_ENV}"
+          fi
 
       - run: echo "${{ env.new_array }}"  
 
