testing with env files

diff --git a/.github/workflows/updateIPLists.yml b/.github/workflows/updateIPLists.yml
--- a/.github/workflows/updateIPLists.yml
+++ b/.github/workflows/updateIPLists.yml
@@ -43,25 +43,23 @@ jobs:
         id: newAllowlistedIpList
         run: |
           new_array=$(curl -s --data "resp_format=json" https://my.imperva.com/api/integration/v1/ips | jq '.ipRanges')
-          echo "::set-output name=newAllowlistedIpList::$new_array"
-                          
-      - name: Compare arrays
+          if [[ -z "$new_array" ]]; then
+            echo "::error::Failed to fetch new array."
+            exit 1
+          else
+            echo "$new_array" >> "$GITHUB_ENV"
+          fi
+
+      - run: echo "{{ env.new_array }}"  
+      - name: Compare array"
         id: compare
-        uses: actions/github-script@v4
+        uses: actions/github-script@v6
         with:
           script: |
-            const oldArray = JSON.parse(process.env.OLD_ARRAY);
-            const newArray = JSON.parse(process.env.NEW_ARRAY);
-
-            if (JSON.stringify(oldArray) === JSON.stringify(newArray)) {
-              console.log("Arrays are equal");
-            } else {
-              console.log("Arrays are not equal");
-              console.log(`Old array: ${JSON.stringify(oldArray)}`);
-              console.log(`New array: ${JSON.stringify(newArray)}`);
-              core.setFailed("Arrays are not equal");
-            }
-
-        env:
-          OLD_ARRAY: ${{ steps.extract.outputs.extractedArray }}
-          NEW_ARRAY: ${{ steps.newAllowlistedIpList.outputs.newAllowlistedIpList }}
+            echo "Old array: ${{ steps.extract.outputs.extractedArray }}"
+            echo "New array: ${{ env.new_array }}"
+            if [[ "${{ steps.readJson.outputs.array }}" == "${{ env.new_array }}" ]]; then
+              echo "The arrays are equal."
+            else
+              echo "The arrays are different."
+            fi
